title: Heartsooo's Personal Website

author: Heartsooo

navbar-links:
  About Me: "aboutme"
  Notes: "notes"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  GitHub: "https://github.com/Heartsooo"

avatar: "/assets/img/avatar-icon.png"
round-avatar: true

social-network-links:
  email: "liuchengxin@shu.edu.cn"
  github: Heartsooo


rss-description: Welcome to Heartsooo's personal website

share-links-active:
  twitter: true
  facebook: false
  linkedin: true
  reddit: false

url-pretty: "Heartsooo.github.io"

title-on-all-pages: true

excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
navbar-var-length: false

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

date_format: "%B %-d, %Y"

timezone: "Asia/Shanghai"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: true
  - scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
